name: Java CI

on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build and Publish with Gradle
        uses: gradle/gradle-build-action@v2
        env:
          MAVEN_REPO_USER: ${{ secrets.MAVEN_REPO_USER }}
          MAVEN_REPO_SECRET: ${{ secrets.MAVEN_REPO_SECRET }}
        with:
          arguments: build publish --stacktrace --no-daemon